"""make submitted_by nullable

Revision ID: 3eb3f4580437
Revises: 
Create Date: 2026-03-10 18:56:21.717927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb3f4580437'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_submissions', 'submitted_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_submissions', 'submitted_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
